### ISSUE TITLE
Expand typecheck to include test files

### ISSUE THREAD

**Issue by chfoidl** [wunderwerkio/drupal-kit#17]
Test files should also be included when running the `typecheck` command.

## Tasks

- [ ] Add separate `tsconfig.json` to typecheck test files with custom configuration (e.g. `skipLibCheck`)
- [ ] Add separate typecheck commands for source and test files
- [ ] Modify `typecheck` command to utilize `pnpm run` to run the two typecheck commands in parallel
